version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mini_insta_pay
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
    depends_on:
      - postgres

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
    depends_on:
      - postgres

  reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
    depends_on:
      - postgres

volumes:
  postgres_data:
