services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mini_insta_pay
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mini_insta_pay"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mini-insta-net-dev

  user-service:
    build: ./user-service
    container_name: user-service-dev
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
      - JWT_SECRET=dev-jwt-secret
    volumes:
      - ./user-service:/app
      - /app/node_modules
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mini-insta-net-dev

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service-dev
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
      - USER_SERVICE_URL=http://user-service:8000
    volumes:
      - ./transaction-service:/app
      - /app/node_modules
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - mini-insta-net-dev

  reporting-service:
    build: ./reporting-service
    container_name: reporting-service-dev
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
      - USER_SERVICE_URL=http://user-service:8000
    volumes:
      - ./reporting-service:/app
      - /app/node_modules
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - mini-insta-net-dev
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_dev:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - mini-insta-net-dev

volumes:
  postgres_data_dev:
  prometheus_data_dev:
  
networks:
  mini-insta-net-dev:
    driver: bridge 