version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mini_insta_pay
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mini-insta-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
    depends_on:
      - postgres
    networks:
      - mini-insta-net

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
    depends_on:
      - postgres
    networks:
      - mini-insta-net

  reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/mini_insta_pay
    depends_on:
      - postgres
    networks:
      - mini-insta-net
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - mini-insta-net

volumes:
  postgres_data:
  prometheus_data:

networks:
  mini-insta-net:
    driver: bridge
