version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-prod
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=mini_insta_pay
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always

  user-service:
    build: ./user-service
    container_name: user-service-prod
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@postgres:5432/mini_insta_pay
      - JWT_SECRET=${JWT_SECRET:-prod-jwt-secret}
    restart: always
    depends_on:
      - postgres

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service-prod
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@postgres:5432/mini_insta_pay
      - USER_SERVICE_URL=http://user-service:8000
    restart: always
    depends_on:
      - postgres
      - user-service

  reporting-service:
    build: ./reporting-service
    container_name: reporting-service-prod
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@postgres:5432/mini_insta_pay
      - USER_SERVICE_URL=http://user-service:8000
    restart: always
    depends_on:
      - postgres
      - user-service

volumes:
  postgres_data_prod: 