global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service-dev:8000']

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service-dev:8001']

  - job_name: 'reporting-service'
    static_configs:
      - targets: ['reporting-service-dev:8002']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 